"""Small display-only localization layer.

Game data remains keyed by the canonical English IDs.  This module only
changes text shown to the user, so profiles remain portable and compatible
with upstream D4LF.
"""

from PyQt6.QtCore import QEvent, QObject
from PyQt6.QtWidgets import (
    QAbstractButton,
    QApplication,
    QComboBox,
    QGroupBox,
    QLabel,
    QLineEdit,
    QListWidget,
    QTabWidget,
    QWidget,
)

from src.settings import get_settings

KO_KR: dict[str, str] = {
    "Dashboard": "대시보드",
    "Full Logs": "전체 로그",
    "ACTIVE PROFILES": "활성 프로필",
    "KEYBOARD SHORTCUTS": "키보드 단축키",
    "EQUIPPED GEAR STATUS": "착용 장비 상태",
    "Scan Equipped Gear": "착용 장비 스캔",
    "Scanning equipped gear...": "착용 장비를 확인하고 있습니다...",
    "Select an active profile first.": "먼저 활성 프로필을 선택하세요.",
    "Game connection is not ready.": "게임 연결을 기다리고 있습니다.",
    "Complete": "완성",
    "Needs work": "보완 필요",
    "Not read": "확인 안 됨",
    "No profile target": "프로필 기준 없음",
    "Weapon": "무기",
    "Greater affixes needed": "상급 옵션 부족",
    "Actual value": "실제 수치",
    "Roll %": "범위 %",
    "0-100": "0~100",
    "Min value": "최소 수치",
    "Actual value compares the number shown in-game. Roll % compares its position within the item's min-max range.": "실제 수치는 게임에 표시된 숫자를 비교합니다. 범위 %는 해당 옵션의 최소~최대 범위 안에서의 위치를 비교합니다.",
    "Roll %: 80 means the value must reach at least 80% of its possible roll range. A missing range cannot pass.": "범위 %에서 80은 가능한 옵션 범위의 80% 이상을 뜻합니다. 범위 정보가 없으면 통과하지 않습니다.",
    "Enter the number shown in-game: +5.9% uses 5.9; +2703 Life uses 2703. Leave blank for no minimum.": "게임 표시 숫자를 입력하세요: +5.9%는 5.9, 생명력 +2703은 2703입니다. 비우면 최소 수치를 적용하지 않습니다.",
    "Remove the entire affix pool instead of its last option.": "마지막 옵션 대신 옵션 묶음 전체를 제거하세요.",
    "Checked = include in filter; unchecked = exclude": "체크 = 찾을 옵션에 포함 · 해제 = 제외",
    "Find": "찾기",
    "Excluded": "제외",
    "Affix filter": "옵션 필터",
    "The last included option cannot be excluded. Remove the slot filter in the editor.": "마지막 찾기 옵션은 해제할 수 없습니다. 부위 필터를 편집기에서 제거하세요.",
    "No equipped gear scan yet. Hover over equipped items to check their profile options.": "아직 착용 장비를 확인하지 않았습니다. 착용 아이템에 마우스를 올리면 프로필 옵션을 확인합니다.",
    "No equipped gear scan yet. Open the character screen and press Scan Equipped Gear.": "캐릭터 장비창을 열고 '착용 장비 스캔'을 누르세요.",
    "Toggle profiles to enable them. Drag <b>⠿</b> to set priority; the top profile determines affix highlighting.": "프로필을 선택해 활성화하세요. <b>⠿</b>를 끌어 우선순위를 정할 수 있으며, 맨 위 프로필이 옵션 강조 표시를 결정합니다.",
    "Filter profiles...": "프로필 검색...",
    "Enable All": "모두 활성화",
    "Disable All": "모두 비활성화",
    "Show Activity Log": "활동 로그 표시",
    "Import Profile": "프로필 가져오기",
    "Settings": "설정",
    "Minimize to Tray": "트레이로 최소화",
    "Profile Editor": "프로필 편집기",
    "Profile": "프로필",
    "Save": "저장",
    "Undo Changes": "변경 취소",
    "Instructions": "안내",
    "Select a profile from the dropdown. Click 'Save' to save your changes. Click 'Undo Changes' to revert your changes.": "목록에서 프로필을 선택하세요. '저장'을 누르면 변경 사항을 저장하고, '변경 취소'를 누르면 되돌립니다.",
    "Affixes": "옵션",
    "Charms": "부적",
    "Seals": "인장",
    "Aspect Upgrades": "위상 업그레이드",
    "Sigils": "악몽 던전 인장",
    "Tributes": "공물",
    "Uniques": "고유 아이템",
    "Create Item": "아이템 추가",
    "Remove Item": "아이템 제거",
    "Set All Min GAs (Excludes Auto Synced Items)": "최소 상급 옵션 수 일괄 설정 (자동 동기화 제외)",
    "Convert All To Min %": "모두 최소 % 방식으로 변경",
    "Set all minPower": "최소 아이템 위력 일괄 설정",
    "Item Types:": "아이템 종류:",
    "Rarities:": "희귀도:",
    "Minimum Power:": "최소 아이템 위력:",
    "Min Greater Affixes:": "최소 상급 옵션 수:",
    "Auto Sync": "자동 동기화",
    "Unique Aspects": "고유 위상",
    "Affix Pool": "옵션 묶음",
    "Inherent Pool": "고유 속성 묶음",
    "Add Affix Pool": "옵션 묶음 추가",
    "Add Inherent Pool": "고유 속성 묶음 추가",
    "Remove Affix Pool": "옵션 묶음 제거",
    "Remove Inherent Pool": "고유 속성 묶음 제거",
    "Add Affix": "옵션 추가",
    "Remove Affix": "옵션 제거",
    "Greater": "상급",
    "Mode": "방식",
    "Threshold": "기준값",
    "Min Count:": "최소 개수:",
    "Max Count:": "최대 개수:",
    "Value": "수치",
    "All rarities": "모든 희귀도",
    "Select Item Types": "아이템 종류 선택",
    "Weapons": "무기",
    "Non-weapons": "무기 외 장비",
    "One-handed Weapons": "한손 무기",
    "Two-handed Weapons": "양손 무기",
    "Off-hand Items": "보조 장비",
    "Other Items": "방어구·장신구·기타",
    "Select Category": "이 분류 모두 선택",
    "Clear Category": "이 분류 선택 해제",
    "If no item types are selected, all item types will be evaluated for this filter.": "선택하지 않으면 모든 아이템 종류를 이 필터로 판정합니다.",
    "Select Rarities": "희귀도 선택",
    "If no rarities are selected, all rarities will be kept for this filter.": "선택하지 않으면 모든 희귀도를 유지합니다.",
    "Clear": "선택 해제",
    "Search settings...": "설정 검색...",
    "Key Bindings": "단축키",
    "Technical Settings": "기술 설정",
    "General": "일반",
    "Filtering": "필터링",
    "Item Handling": "아이템 처리",
    "Display & Overlay": "화면 및 오버레이",
    "Auto-use Temper Manuals": "담금질 설명서 자동 사용",
    "Browser": "브라우저",
    "Stash Tabs to Filter": "필터링할 보관함 탭",
    "Protective Ancestral Filter": "선조 전설 보호 필터",
    "Filter Equipment": "장비 필터링",
    "Filter Sigils": "인장 필터링",
    "Filter Tributes": "공물 필터링",
    "Filter Seals": "봉인 필터링",
    "Filter Charms": "부적 필터링",
    "Full Dump": "전체 데이터 가져오기",
    "Handle Cosmetics": "꾸미기 아이템 처리",
    "Unfiltered Unique Behavior": "미일치 고유 아이템 처리",
    "Ignore Escalation Sigils": "승급 인장 제외",
    "Aspect Upgrade Handling": "위상 업그레이드 처리",
    "Language": "언어",
    "Mark Matched Items as Favorite": "일치 아이템 즐겨찾기",
    "Max Stash Tabs": "최대 보관함 탭 수",
    "Overlay Text Size": "오버레이 글자 크기",
    "Move to Inventory Types": "소지품으로 옮길 종류",
    "Move to Stash Types": "보관함으로 옮길 종류",
    "Auto-Start Vision Mode": "화면 인식 자동 시작",
    "Theme": "테마",
    "Colorblind Accessible Palette": "색각 보정 팔레트",
    "Vision Mode Type": "화면 인식 방식",
    "Inventory Hotkey": "소지품 단축키",
    "Disable TTS Warning": "TTS 경고 끄기",
    "Exit Key": "종료 단축키",
    "Fast Vision Mode Coordinates": "빠른 화면 인식 오버레이 위치",
    "Force Refresh Only": "상태만 강제 초기화",
    "Info Overlay": "정보 오버레이",
    "Logging Detail Level": "로그 상세 수준",
    "Show Timestamps In Logs": "로그에 시간 표시",
    "Show Technical Information In Logs": "로그에 기술 정보 표시",
    "Move To Chest": "보관함으로 이동",
    "Move To Inv": "소지품으로 이동",
    "Diablo IV Process Name": "Diablo IV 프로세스 이름",
    "Run Filter": "필터 실행",
    "Run Stash Filter": "보관함 필터 실행",
    "Run Filter Drop": "필터 실행 후 버리기",
    "Run Filter Force Refresh": "초기화 후 필터 실행",
    "Run Vision Mode": "화면 인식 실행",
    "Toggle Paragon Overlay": "정복자 오버레이 전환",
    "Vision Mode Only": "화면 인식 전용 모드",
    "Vision Mode: STOPPED": "화면 인식: 중지",
    "Vision Mode: RUNNING": "화면 인식: 실행 중",
    "TTS: Disconnected": "TTS: 연결 안 됨",
    "TTS: Connected": "TTS: 연결됨",
    "Edit": "편집",
    "Delete": "삭제",
    "Edit Profile": "프로필 편집",
    "Delete Profile": "프로필 삭제",
    "No Profiles found. Please import a profile below.": "프로필이 없습니다. 아래에서 프로필을 가져오세요.",
    "Log:": "로그:",
    "Instructions:": "안내:",
    "URL:": "URL:",
    "Generate": "생성",
    "Custom file name:": "사용자 지정 파일 이름:",
    "Leave blank for default filename": "비워 두면 기본 파일 이름을 사용합니다",
    "Default filename includes...": "기본 파일 이름 구성...",
    "Reset Settings": "설정 초기화",
    "Reset All Tabs": "모든 탭 초기화",
    "Reset to defaults": "기본값으로 초기화",
    "Set Hotkey": "단축키 설정",
    "Press the key or combination of keys you\nwant to use as a hotkey, then click save.": "사용할 키 또는 키 조합을 누른 뒤\n저장을 클릭하세요.",
    "Cancel": "취소",
    "OK": "확인",
    "Warning": "경고",
    "Error": "오류",
    "Info": "정보",
    "Alert": "알림",
    "Restart required": "다시 시작 필요",
    "Restart now": "지금 다시 시작",
    "Later": "나중에",
    "Restart failed": "다시 시작 실패",
    "Error validating value": "값 확인 오류",
    "Add Tribute": "공물 추가",
    "Remove Selected": "선택 항목 제거",
    "Create Tribute": "공물 생성",
    "Tribute:": "공물:",
    "Add Tribute Rarity": "공물 희귀도 추가",
    "Rarity:": "희귀도:",
    "Delete Tributes": "공물 삭제",
    "Select Tributes to delete:": "삭제할 공물을 선택하세요:",
    "None": "없음",
    "Add Aspect": "위상 추가",
    "Remove Aspect": "위상 제거",
    "Aspect:": "위상:",
    "Aspect": "위상",
    "Add Unique Aspect": "고유 위상 추가",
    "Remove Unique Aspect": "고유 위상 제거",
    "Add Sigil": "인장 추가",
    "Remove Whitelist Sigil": "허용 인장 제거",
    "Remove Blacklist Sigil": "제외 인장 제거",
    "Create Sigil": "인장 생성",
    "Kind:": "분류:",
    "Name:": "이름:",
    "Type: ": "종류: ",
    "Delete Blacklist Sigil": "제외 인장 삭제",
    "Delete Whitelist Sigil": "허용 인장 삭제",
    "Blacklist": "제외 목록",
    "Whitelist": "허용 목록",
    "Select Sigils to delete:": "삭제할 인장을 선택하세요:",
    "Add Condition": "조건 추가",
    "Remove Condition": "조건 제거",
    "Condition": "조건",
    "Delete Items": "아이템 삭제",
    "Items": "아이템",
    "Select items to delete:": "삭제할 항목을 선택하세요:",
    "Item Name:": "아이템 이름:",
    "Delete Inherent Pool": "고유 속성 묶음 삭제",
    "Delete Affix Pool": "옵션 묶음 삭제",
    "Percent (0-100)": "백분율 (0-100)",
    "Value (optional)": "수치 (선택 사항)",
    "Profile Importer - d2core / Maxroll / D4Builds / Mobalytics / InfinityBuilds": "프로필 가져오기 - d2core / Maxroll / D4Builds / Mobalytics / InfinityBuilds",
    "D4 Loot Filter": "D4 전리품 필터",
    "D4LF settings error": "D4LF 설정 오류",
    "GlobalUniques": "전체 고유 아이템",
    "Global Unique Rule": "전체 고유 아이템 규칙",
    "Create Rule": "규칙 추가",
    "Remove Rule": "규칙 제거",
    "Profile Alias:": "프로필 별칭:",
    "Priority:": "우선순위:",
    "Min Percent of Aspect:": "위상 최소 수치(%):",
    "Sets:": "세트:",
    "No profiles found": "프로필 없음",
    "Unsaved Changes": "저장하지 않은 변경 사항",
    "Profile Validation Failed": "프로필 검증 실패",
    "Validation Error": "검증 오류",
    "Profile not saved.": "프로필이 저장되지 않았습니다.",
    "Saving...": "저장 중...",
    "Generating...": "생성 중...",
    "Select variants to import": "가져올 변형 선택",
    "Name cannot be empty": "이름을 입력하세요.",
    "Name already exists": "같은 이름이 이미 있습니다.",
    "Item name cannot be empty": "아이템 이름을 입력하세요.",
    "Item name already exist": "같은 아이템 이름이 이미 있습니다.",
    "Min % must be between 0 and 100.": "최소 %는 0에서 100 사이여야 합니다.",
    "All unique aspects have already been added.": "모든 고유 위상이 이미 추가되었습니다.",
    "Cannot add unique aspects when sets are selected.": "세트를 선택한 상태에서는 고유 위상을 추가할 수 없습니다.",
    "Cannot select sets when unique aspects are defined.": "고유 위상이 설정된 상태에서는 세트를 선택할 수 없습니다.",
    "Add tribute names and select rarities you want to keep. Leaving rarities empty keeps all rarities.": "유지할 공물과 희귀도를 선택하세요. 희귀도를 비워 두면 모든 희귀도를 유지합니다.",
    "Select a valid tribute from the list.": "목록에서 올바른 공물을 선택하세요.",
    "Tribute already exist. You can modify the existing one.": "이미 등록된 공물입니다. 기존 항목을 수정하세요.",
    "Select a valid rarity from the list.": "목록에서 올바른 희귀도를 선택하세요.",
    "Rarity already exists in this tribute filter.": "이 공물 필터에 같은 희귀도가 이미 있습니다.",
    "Select at least one tribute rule to remove.": "삭제할 공물 규칙을 하나 이상 선택하세요.",
    "Sigil already exist in blacklist. You can modify the existing one.": "이미 제외 목록에 있는 인장입니다. 기존 항목을 수정하세요.",
    "Sigil already exist in whitelist. You can modify the existing one.": "이미 허용 목록에 있는 인장입니다. 기존 항목을 수정하세요.",
    "The profile model might not be valid. Do you still want to save your changes ?": "프로필 설정이 올바르지 않을 수 있습니다. 그래도 변경 사항을 저장하시겠습니까?",
    "You have unsaved changes. Do you want to save them before closing?": "저장하지 않은 변경 사항이 있습니다. 닫기 전에 저장하시겠습니까?",
    "This will reset ALL custom values in your params.ini. Are you sure?": "params.ini의 모든 사용자 설정을 초기화합니다. 계속하시겠습니까?",
    "Vision mode changes require restarting d4lf. Restart now?": "화면 인식 방식 변경을 적용하려면 D4LF를 다시 시작해야 합니다. 지금 다시 시작하시겠습니까?",
    "d4lf could not be restarted automatically. Please restart it manually.": "D4LF를 자동으로 다시 시작하지 못했습니다. 직접 다시 실행해 주세요.",
    "TTS: Disabled (GUI-only)": "TTS: 비활성화 (화면 전용)",
    "Vision Mode: Disabled (GUI-only)": "화면 인식: 비활성화 (화면 전용)",
    "(1 greater affix marked)": "(상급 옵션 1개 선택됨)",
    "(no greater affixes marked)": "(선택된 상급 옵션 없음)",
    "Minimum number of checked affixes that must be Greater Affixes.": "선택한 옵션 중 상급 옵션이어야 하는 최소 개수입니다.",
    "0 = Accept items even without GAs (for leveling)\n1-4 = At least this many checked affixes must be GA": "0 = 상급 옵션이 없어도 허용 (레벨링용)\n1-4 = 선택한 옵션 중 해당 개수 이상이 상급 옵션이어야 함",
    "When checked: Min Greater Affixes automatically matches the number of affixes marked as 'want greater'": "선택 시: 최소 상급 옵션 수가 '상급'으로 지정한 옵션 개수와 자동으로 일치합니다.",
    "When unchecked: You can manually set Min Greater Affixes to any value": "해제 시: 최소 상급 옵션 수를 직접 설정할 수 있습니다.",
    "Enter a URL to generate a profile.": "프로필을 생성할 URL을 입력하세요.",
    "Active Filtering Profiles": "활성 필터 프로필",
    "Which filter profiles should be run.": "실행할 필터 프로필을 선택합니다.",
    "Do not mark ancestral legendaries as junk": "선조 전설 아이템을 폐품으로 표시하지 않습니다.",
    "Enable colorblind palette": "색각 보정 팔레트를 사용합니다.",
    "GUI Theme": "화면 테마",
    "Hotkey in Diablo IV to open inventory": "Diablo IV에서 소지품을 여는 단축키입니다.",
    "Hotkey to enable/disable the vision mode": "화면 인식을 켜거나 끄는 단축키입니다.",
    "Hotkey to exit d4lf": "D4LF를 종료하는 단축키입니다.",
    "Hotkey to move configured items from inventory to stash": "설정한 아이템을 소지품에서 보관함으로 옮기는 단축키입니다.",
    "Hotkey to move configured items from stash to inventory": "설정한 아이템을 보관함에서 소지품으로 옮기는 단축키입니다.",
    "Hotkey to open/close the Paragon overlay": "정복자 오버레이를 열거나 닫는 단축키입니다.",
    "Hotkey to open/close the info panel overlay": "정보 오버레이를 열거나 닫는 단축키입니다.",
    "Hotkey to refresh the junk/favorite status of all items in your inventory/stash. A filter is not run after.": "소지품과 보관함의 즐겨찾기/폐품 상태를 초기화합니다. 초기화 후 필터는 실행하지 않습니다.",
    "Hotkey to run the filter process with a force refresh. The status of all junk/favorite items will be reset": "즐겨찾기/폐품 상태를 초기화한 뒤 필터를 실행하는 단축키입니다.",
    "Hotkey to run the filter process. If the item matches no profiles, it is dropped.": "필터를 실행하고 프로필과 일치하지 않는 아이템을 버리는 단축키입니다.",
    "Hotkey to run the filter process. If the item matches no profiles, it is marked as junk.": "필터를 실행하고 프로필과 일치하지 않는 아이템을 폐품으로 표시하는 단축키입니다.",
    "Hotkey to filter character inventory only. If an item matches no profile, it is marked as junk.": "소지품만 필터링합니다. 프로필과 일치하지 않는 아이템은 폐품으로 표시합니다.",
    "Hotkey to filter configured stash tabs only. The stash must be open.": "설정한 보관함 탭만 필터링합니다. 보관함을 연 상태에서 사용하세요.",
    "If TTS is working for you but you are still receiving the warning, check this box to disable it.": "TTS가 정상 작동하지만 경고가 계속 표시되면 이 옵션을 켜세요.",
    "Include technical information (thread, level, logger name, line number) in Dashboard and Full Logs messages. Log files always include this information.": "대시보드와 전체 로그에 스레드, 로그 수준, 모듈명, 줄 번호를 표시합니다. 로그 파일에는 항상 기록됩니다.",
    "Include timestamps in Dashboard and Full Logs messages. Log files always include timestamps.": "대시보드와 전체 로그에 시간을 표시합니다. 로그 파일에는 항상 기록됩니다.",
    "Language used for Diablo 4 TTS parsing. Supported values: enUS, koKR": "Diablo IV TTS 분석에 사용할 언어입니다. 지원 언어: enUS, koKR",
    "Only allow vision mode to run. All hotkeys and actions that click will be disabled.": "화면 인식만 실행합니다. 클릭을 수행하는 단축키와 자동화 기능은 비활성화됩니다.",
    "Should the vision mode use the slightly slower version that highlights matching affixes, or the immediate version that just shows text of the matches? Note: highlight_matches does not work with controllers.": "일치 옵션을 직접 강조하는 방식과 결과 텍스트만 표시하는 빠른 방식 중에서 선택합니다. 옵션 강조 방식은 컨트롤러에서 작동하지 않습니다.",
    "The level at which logs are written": "기록할 로그의 상세 수준입니다.",
    "The maximum number of stash tabs available.": "사용 가능한 보관함 탭의 최대 개수입니다.",
    "The minimum font size for the vision overlays.": "화면 인식 오버레이의 최소 글자 크기입니다.",
    "The process that is running Diablo 4. You should never need to change this.": "Diablo IV 실행 프로세스 이름입니다. 일반적으로 변경할 필요가 없습니다.",
    "The top left coordinates of the desired location of the fast vision mode overlay in pixels. For example: (300, 500). Set to blank for default behavior.": "빠른 화면 인식 오버레이의 왼쪽 위 좌표입니다. 예: (300, 500). 기본 위치를 사용하려면 비워 두세요.",
    "What should be done with cosmetic upgrades that do not match any filter": "필터와 일치하지 않는 꾸미기 업그레이드의 처리 방법입니다.",
    "What should be done with uniques that do not match any profile. Mythics are always favorited. If mark_as_favorite is unchecked then uniques that match a profile will not be favorited.": "프로필과 일치하지 않는 고유 아이템의 처리 방법입니다. 신화 아이템은 항상 즐겨찾기로 표시됩니다. '일치 아이템 즐겨찾기'를 끄면 프로필과 일치한 고유 아이템도 즐겨찾기로 표시하지 않습니다.",
    "When doing stash/inventory transfer, what types of items should be moved": "보관함과 소지품 사이에서 옮길 아이템 표시 종류를 선택합니다.",
    "When filtering Sigils, should escalation sigils be ignored?": "인장 필터링 시 승급 인장을 제외할지 선택합니다.",
    "When using the import build feature, whether to use the full dump (e.g. contains all filter items) or not": "빌드를 가져올 때 모든 필터 아이템이 포함된 전체 데이터를 사용할지 선택합니다.",
    "When using the loot filter, should found temper manuals be automatically used? Note: Will not work with stash open.": "전리품 필터가 담금질 설명서를 발견하면 자동으로 사용합니다. 보관함이 열린 상태에서는 작동하지 않습니다.",
    "Whether to favorite matched items or not": "필터와 일치한 아이템을 즐겨찾기로 표시합니다.",
    "Whether to keep aspects that didn't match a filter": "필터와 일치하지 않는 위상의 유지 방법을 선택합니다.",
    "Whether to run vision mode on startup or not": "프로그램 시작 시 화면 인식을 자동으로 실행합니다.",
    "Which browser to use to get builds": "빌드를 가져올 때 사용할 브라우저입니다.",
    "Which stash tabs to check. Note: All tabs available (6 or 7) must be unlocked!": "검사할 보관함 탭을 선택합니다. 설정한 6개 또는 7개 탭이 모두 잠금 해제되어 있어야 합니다.",
    "favorite": "즐겨찾기",
    "junk": "폐품",
    "unmarked": "표시 없음",
    "ignore": "무시",
    "keep": "유지",
    "drop": "버리기",
    "dark": "어둡게",
    "light": "밝게",
    "debug": "디버그",
    "info": "정보",
    "warning": "경고",
    "error": "오류",
    "highlight_matches": "일치 옵션 강조",
    "text_only": "결과 텍스트만 표시",
    "No process named Diablo IV.exe was found and unable to automatically determine if TTS DLL is installed.": "Diablo IV.exe 프로세스를 찾지 못해 TTS DLL 설치 여부를 자동으로 확인할 수 없습니다.",
    "Unable to find a Diablo 4 local prefs file. Can't automatically check if TTS is configured properly in-game. If d4lf is working without issue for you, you can disable this warning by enabling 'disable_tts_warning' in the Advanced settings.": "Diablo IV 로컬 설정 파일을 찾지 못해 게임 내 TTS 설정을 자동으로 확인할 수 없습니다. D4LF가 정상 작동한다면 고급 설정에서 'TTS 경고 끄기'를 활성화하세요.",
    "Minimum number of checked affixes that must be Greater Affixes.\n0 = Accept items even without GAs (for leveling)\n1-4 = At least this many checked affixes must be GA": "선택한 옵션 중 상급 옵션이어야 하는 최소 개수입니다.\n0 = 상급 옵션이 없어도 허용 (레벨링용)\n1-4 = 선택한 옵션 중 해당 개수 이상이 상급 옵션이어야 함",
    "When checked: Min Greater Affixes automatically matches the number of affixes marked as 'want greater'\nWhen unchecked: You can manually set Min Greater Affixes to any value": "선택 시: 최소 상급 옵션 수가 '상급'으로 지정한 옵션 개수와 자동으로 일치합니다.\n해제 시: 최소 상급 옵션 수를 직접 설정할 수 있습니다.",
}


def is_korean() -> bool:
    return get_settings().general.language.casefold() == "kokr"


def tr(text: str) -> str:
    return KO_KR.get(text, text) if is_korean() else text


def localize_widget_tree(root: QWidget) -> None:
    """Translate text for widgets, including lazily-created dialogs."""
    if not is_korean():
        return
    widgets = [root, *root.findChildren(QWidget)]
    for widget in widgets:
        if widget.windowTitle():
            widget.setWindowTitle(tr(widget.windowTitle()))
        if widget.toolTip():
            widget.setToolTip(tr(widget.toolTip()))
        if isinstance(widget, (QAbstractButton, QLabel)) and widget.text():
            widget.setText(tr(widget.text()))
        if isinstance(widget, QGroupBox) and widget.title():
            widget.setTitle(tr(widget.title()))
        if isinstance(widget, QLineEdit) and widget.placeholderText():
            widget.setPlaceholderText(tr(widget.placeholderText()))
        if isinstance(widget, QComboBox):
            for index in range(widget.count()):
                localized = tr(widget.itemText(index))
                if localized != widget.itemText(index):
                    widget.setItemText(index, localized)
        if isinstance(widget, QTabWidget):
            for index in range(widget.count()):
                widget.setTabText(index, tr(widget.tabText(index)))
        if isinstance(widget, QListWidget):
            for index in range(widget.count()):
                item = widget.item(index)
                if item is not None:
                    item.setText(tr(item.text()))


class _UiLocalizer(QObject):
    def eventFilter(self, watched: QObject, event: QEvent) -> bool:  # ruff: ignore[invalid-function-name]
        if event.type() in (QEvent.Type.Show, QEvent.Type.Polish) and isinstance(watched, QWidget):
            localize_widget_tree(watched)
        return False


_UI_LOCALIZER: _UiLocalizer | None = None


def install_ui_localizer(app: QApplication) -> None:
    global _UI_LOCALIZER
    if not is_korean() or _UI_LOCALIZER is not None:
        return
    _UI_LOCALIZER = _UiLocalizer(app)
    app.installEventFilter(_UI_LOCALIZER)
